#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
filename="${DIR}/config"

while read -r line
do
    if [ -z "${line}" ]; then
        continue
    elif [[ $line == //* ]]; then
        continue
    else
        from=$(echo "$line" | awk 'BEGIN{FS=" : "}{print $1}')
        to=$(echo "$line" | awk 'BEGIN{FS=" : "}{print $2}')

        echo "Processing: $line"
        to_path=""${HOME}/${to}""
        from_path=""${DIR}/${from}""

        if [ ! -L "$to_path" ]; then
            # symlink doesn't exist. Let's create it
            echo "Creating symlink:"
            echo "$from_path -> $to_path"

            ln -s $from_path $to_path
        #else
            #echo "Symlink already exists: $to_path"
        fi
    fi
done < "$filename"